final Map<String, String> signToUrdu = {
  // -------- DICTIONARY --------
  "PSL_DICTIONARY": "پی ایس ایل لغت",

  // -------- GREETINGS & BASIC PHRASES --------
  "HELLO": "ہیلو",
  "ASSALAM_O_ALAIKUM": "السلام علیکم",
  "WALAIKUM_AS_SALAAM": "وعلیکم السلام",
  "GOOD_MORNING": "صبح بخیر",
  "GOOD_AFTERNOON": "سہ پہر بخیر",
  "GOOD_EVENING": "شام بخیر",
  "GOOD_NIGHT": "شب بخیر",
  "GOODBYE": "الوداع",
  "SEE_YOU_LATER": "پھر ملیں گے",
  "I_LL_SEE_YOU_LATER": "میں آپ سے بعد میں ملوں گا",
  "WELCOME": "خوش آمدید",
  "THANK_YOU": "شکریہ",
  "PLEASE": "براہ کرم",
  "EXCUSE_ME": "معاف کیجیے",
  "CONGRATULATIONS": "مبارک ہو",
  "EID_MUBARAK": "عید مبارک",
  "EID": "عید",
  "HAPPY_NEW_YEAR": "نیا سال مبارک",
  "HAVE_A_NICE_DAY": "اچھا دن گزاریں",
  "NICE_TO_MEET_YOU": "آپ سے مل کر خوشی ہوئی",
  "WELL_DONE": "شاباش",
  "WOW_EXCITEMENT": "واہ",

  // -------- QUESTIONS (HOW/WHAT/WHERE/WHEN/WHO/WHY) --------
  "HOW_ARE_YOU": "آپ کیسے ہیں",
  "HOW": "کیسے",
  "HOW_QUESTION": "کیسے",
  "HOW_CAN_I_HELP_YOU": "میں آپ کی کیسے مدد کر سکتا ہوں",
  "HOW_DO_I_GET_THERE": "میں وہاں کیسے پہنچوں",
  "HOW_DO_YOU_FEEL": "آپ کیسا محسوس کر رہے ہیں",
  "HOW_FAR": "کتنی دور",
  "HOW_FAR_IS_IT": "یہ کتنی دور ہے",
  "HOW_LONG": "کتنی دیر",
  "HOW_LONG_ARE_YOU_STAYING": "آپ کتنی دیر رہیں گے",
  "HOW_MANY": "کتنے",
  "HOW_MANY_CHILDREN_DO_YOU_HAVE": "آپ کے کتنے بچے ہیں",
  "HOW_MUCH": "کتنا",
  "HOW_MUCH_DOES_IT_COST": "اس کی قیمت کتنی ہے",
  "HOW_OFTEN": "کتنی بار",
  "HOW_OLD_ARE_YOU": "آپ کی عمر کتنی ہے",
  
  "WHAT": "کیا",
  "WHAT_FOR": "کس لیے",
  "WHAT_IS_YOUR_NAME": "آپ کا نام کیا ہے",
  "WHAT_IS_YOUR_EMAIL_ADDRESS": "آپ کا ای میل ایڈریس کیا ہے",
  "WHAT_IS_YOUR_E_MAIL_ADDRESS": "آپ کا ای میل ایڈریس کیا ہے",
  "WHAT_IS_YOUR_TELEPHONE_NUMBER": "آپ کا فون نمبر کیا ہے",
  
  "WHERE": "کہاں",
  "WHERE_DO_YOU_LIVE": "آپ کہاں رہتے ہیں",
  
  "WHEN": "کب",
  "WHICH": "کون سا",
  "WHO": "کون",
  "WHOSE": "کس کا",
  "WHY": "کیوں",
  "WITH_WHOM": "کس کے ساتھ",

  // -------- YES/NO & SIMPLE RESPONSES --------
  "MAYBE": "شاید",
  "DOESN_T_MATTER": "کوئی بات نہیں",
  "IT_IS_FINE": "ٹھیک ہے",
  "IT_S_UP_TO_YOU": "آپ کی مرضی",

  // -------- QUESTIONS (ARE/DO/IS/CAN/DID) --------
  "ARE_YOU_DEAF": "کیا آپ بہرے ہیں",
  "ARE_YOU_HUNGRY": "کیا آپ کو بھوک لگی ہے",
  "ARE_YOU_READY": "کیا آپ تیار ہیں",
  
  "DO_YOU_ALLOW_ANIMALS": "کیا آپ جانوروں کی اجازت دیتے ہیں",
  "DO_YOU_FEEL_ALL_RIGHT": "کیا آپ ٹھیک محسوس کر رہے ہیں",
  "DO_YOU_GO_TO_SCHOOL": "کیا آپ سکول جاتے ہیں",
  "DO_YOU_HAVE_A_PET": "کیا آپ کا کوئی پالتو جانور ہے",
  "DO_YOU_HAVE_ANY_ASPIRIN": "کیا آپ کے پاس ایسپرین ہے",
  "DO_YOU_HAVE_MORE_OF_THIS": "کیا آپ کے پاس اس میں سے مزید ہے",
  "DO_YOU_KNOW_WHERE_I_CAN_FIND_A_ROOM_HERE": "کیا آپ جانتے ہیں کہ مجھے یہاں کمرہ کہاں مل سکتا ہے",
  "DO_YOU_LIKE_TO_WATCH_TV": "کیا آپ ٹی وی دیکھنا پسند کرتے ہیں",
  "DO_YOU_SPEAK_ENGLISH": "کیا آپ انگریزی بولتے ہیں",
  "DO_YOU_USE_A_HEARING_AID": "کیا آپ سماعت کی مشین استعمال کرتے ہیں",
  "DO_YOU_WANT_A_SOFT_DRINK": "کیا آپ سافٹ ڈرنک چاہتے ہیں",
  "DO_YOU_WANT_MILK_AND_SUGAR": "کیا آپ دودھ اور چینی چاہتے ہیں",
  "DO_YOU_WANT_TO_GO_TO_THE_MOVIES": "کیا آپ فلم دیکھنے جانا چاہتے ہیں",
  
  "DID_YOU_ASK_HIM": "کیا آپ نے اس سے پوچھا",
  "DID_YOU_EAT": "کیا آپ نے کھایا",
  "DID_YOU_PASS_OR_FAIL": "کیا آپ پاس ہوئے یا فیل",
  "DID_YOU_UNDERSTAND": "کیا آپ سمجھے",
  
  "CAN_I_HELP_YOU": "کیا میں آپ کی مدد کر سکتا ہوں",
  "CAN_I_TAKE_YOUR_ORDER": "کیا میں آپ کا آرڈر لے سکتا ہوں",
  "CAN_I_USE_THE_TOILET": "کیا میں بیت الخلا استعمال کر سکتا ہوں",
  
  "IS_IT_BROKEN": "کیا یہ ٹوٹا ہوا ہے",
  "IS_IT_FAR_FROM_HERE": "کیا یہ یہاں سے دور ہے",
  "IS_IT_TRUE": "کیا یہ سچ ہے",
  "IS_SOMEBODY_MEETING_YOU": "کیا کوئی آپ سے ملنے آ رہا ہے",
  "IS_THAT_ENOUGH_FOR_YOU": "کیا یہ آپ کے لیے کافی ہے",
  
  "HAVE_YOU_EATEN": "کیا آپ نے کھانا کھایا",

  // -------- COMMANDS & REQUESTS --------
  "BEWARE": "خبردار",
  "CALL_THE_AMBULANCE": "ایمبولینس بلائیں",
  "CLOSE_THE_DOOR": "دروازہ بند کریں",
  "CLOSE_THE_WINDOW": "کھڑکی بند کریں",
  "COME_HERE": "یہاں آئیں",
  "COME_VISIT_ME_SOMETIME": "کبھی میرے پاس آئیں",
  "DON_T_TOUCH": "مت چھوئیں",
  "GO_AWAY": "چلے جائیں",
  "SIGN_SLOWLY_PLEASE": "براہ کرم آہستہ اشارہ کریں",
  "STAY_HERE_TODAY": "آج یہاں رہیں",

  // -------- PERSONAL STATEMENTS (I AM/I DO/I HAVE/I NEED/I WANT) --------
  "MY_NAME_IS": "میرا نام ہے",
  "I_AM_A_STUDENT": "میں طالب علم ہوں",
  "I_AM_LEARNING_SIGN_LANGUAGE": "میں اشاروں کی زبان سیکھ رہا ہوں",
  "I_AM_STUDYING_TO_BE_AN_INTERPRETER": "میں مترجم بننے کی تعلیم حاصل کر رہا ہوں",
  "I_AM_SICK": "میں بیمار ہوں",
  
  "I_DO_NOT_BELIEVE_YOU": "میں آپ پر یقین نہیں کرتا",
  "I_DO_NOT_LIKE_THIS": "مجھے یہ پسند نہیں",
  "I_DO_NOT_UNDERSTAND": "میں نہیں سمجھا",
  
  "I_HAVE_A_QUESTION": "میرا ایک سوال ہے",
  "I_HAVE_TO_BUY_SOME_MEDICINE": "مجھے کچھ دوائی خریدنی ہے",
  "I_HAVE_TO_GO_SHOPPING": "مجھے خریداری کرنی ہے",
  
  "I_NEED_TO_GO_TO_THE_BANK": "مجھے بینک جانا ہے",
  "I_NEED_TO_WASH_MY_SHIRT": "مجھے اپنی قمیض دھونی ہے",
  "I_NEED_TO_APPLY_FOR_LEAVE": "مجھے چھٹی کے لیے درخواست دینی ہے",
  
  "I_LIKE_TO_COMPLETE_MY_WORK_EARLY": "میں اپنا کام جلدی مکمل کرنا پسند کرتا ہوں",
  "I_SPEAK_A_LITTLE_BIT": "میں تھوڑا سا بولتا ہوں",
  "I_STARTED_A_COMPUTER_CLASS_TODAY": "میں نے آج کمپیوٹر کی کلاس شروع کی",
  "I_STUDIED_ALL_NIGHT": "میں نے ساری رات پڑھائی کی",
  "I_WANT_TO_VISIT_THE_DEAF_CLUB": "میں بہروں کے کلب جانا چاہتا ہوں",
  "I_WAS_BORN_DEAF": "میں پیدائشی بہرا ہوں",
  "I_WENT_TO_A_SCHOOL_FOR_HEARING_CHILDREN": "میں سننے والے بچوں کے سکول گیا",
  "I_WILL_BE_BACK_SOON": "میں جلد واپس آؤں گا",
  "I_WILL_BE_LATE": "میں دیر سے آؤں گا",
  "I_WOULD_LIKE_TO_INTERVIEW_FOR_THIS_JOB": "میں اس نوکری کے لیے انٹرویو دینا چاہتا ہوں",
  "I_FORGOT_TO_BRING_MY_REGISTRATION_CARD": "میں اپنا رجسٹریشن کارڈ لانا بھول گیا",

  // -------- GENERAL STATEMENTS --------
  "IT_WAS_COLD_THIS_MORNING": "آج صبح سردی تھی",
  "LET_S_GO_TO_A_RESTAURANT": "چلیں ریستوران چلتے ہیں",
  "MATH_IS_A_DIFFICULT_SUBJECT_FOR_ME": "ریاضی میرے لیے مشکل مضمون ہے",
  "MAY_I_HAVE_YOUR_BUSINESS_CARD": "کیا میں آپ کا کاروباری کارڈ لے سکتا ہوں",
  "MAYBE_IT_WILL_RAIN_TOMORROW": "شاید کل بارش ہو",
  "MY_BROTHER_IS_YOUNGER_THAN_ME": "میرا بھائی مجھ سے چھوٹا ہے",
  "MY_INTERNET_CONNECTION_IS_SLOW": "میرا انٹرنیٹ کنکشن سست ہے",
  "MY_SIGN_LANGUAGE_HAS_ALREADY_IMPROVED": "میری اشاروں کی زبان پہلے ہی بہتر ہو چکی ہے",
  "NO_TALKING_DURING_THE_TEST": "امتحان کے دوران بات نہیں",
  "SIXTY_THOUSAND_PEOPLE_LIVE_IN_MY_CITY": "میرے شہر میں ساٹھ ہزار لوگ رہتے ہیں",
  "SMOKING_IS_NOT_ALLOWED": "سگریٹ نوشی کی اجازت نہیں",
  "THANK_YOU_FOR_DINING_WITH_US": "ہمارے ساتھ کھانے کا شکریہ",
  "THE_CAKE_IS_IN_THE_OVEN": "کیک اوون میں ہے",
  "THE_FLIGHT_HAS_BEEN_DELAYED_AN_HOUR": "پرواز ایک گھنٹہ تاخیر سے ہے",
  "THE_GARBAGE_TRUCK_COMES_ONCE_A_WEEK": "کچرے کی گاڑی ہفتے میں ایک بار آتی ہے",
  "THE_POLICE_STATION_IS_TWO_BLOCKS_AWAY": "پولیس سٹیشن دو بلاک دور ہے",
  "THE_TEACHER_ASKED_ME_A_LOT_OF_QUESTIONS": "استاد نے مجھ سے بہت سوالات پوچھے",
  "THERE_HAS_BEEN_AN_ACCIDENT": "ایک حادثہ ہوا ہے",
  "THERE_IS_NO_SIGN_FOR_THAT_YOU_HAVE_TO_FINGERSPELL_IT": "اس کا کوئی اشارہ نہیں ہے آپ کو اسے انگلیوں سے لکھنا ہوگا",
  "THIS_IS_VERY_IMPORTANT": "یہ بہت اہم ہے",
  "YOUR_LANGUAGE": "آپ کی زبان",

  // -------- MEDICAL / HEALTH --------
  "AFTER_3_MONTHS_VISIT_AGAIN": "تین ماہ بعد دوبارہ آئیں",
  "ANESTHESIA_OF_EYE_NUMBNESS_OF_EYE": "آنکھ کا بے حسی",
  "ARE_YOU_MUSLIM_OR_NON_MUSLIM": "کیا آپ مسلمان ہیں یا غیر مسلم",
  "ARE_YOU_RECEIVING_TREATMENT_FROM_ANY_OTHER_DOCTOR_OR_HOSPITAL": "کیا آپ کسی اور ڈاکٹر یا ہسپتال سے علاج لے رہے ہیں",
  "ARE_YOU_RENTING_OR_DO_YOU_OWN_YOUR_HOUSE": "کیا آپ کرائے پر ہیں یا آپ کا اپنا گھر ہے",
  "ARE_YOU_TAKING_CONSULTATION_FROM_ANOTHER_DOCTOR": "کیا آپ کسی اور ڈاکٹر سے مشورہ لے رہے ہیں",
  "ARE_YOU_WEARING_GLASSES_FOR_THE_FIRST_TIME": "کیا آپ پہلی بار چشمہ پہن رہے ہیں",
  
  "CHECK_YOUR_FEET_DAILY": "روزانہ اپنے پیروں کی جانچ کریں",
  "CHECKUP_OF_YOUR_EYE_SIGHT": "آپ کی نظر کی جانچ",
  "CHEMICAL_INJURY_OF_EYES": "آنکھوں کی کیمیائی چوٹ",
  "COME_TOMORROW_FOR_SURGERY": "کل سرجری کے لیے آئیں",
  "CUT_YOUR_NAILS_AFTER_BATH_AND_DON_T_CUT_CORNERS": "نہانے کے بعد اپنے ناخن کاٹیں اور کونے نہ کاٹیں",
  
  "DO_YOU_FEEL_DIZZY": "کیا آپ چکر محسوس کرتے ہیں",
  "DO_YOU_FEEL_ITCHING": "کیا آپ کو خارش محسوس ہوتی ہے",
  "DO_YOU_HAVE_ANY_DEBTS": "کیا آپ پر کوئی قرض ہے",
  "DO_YOU_HAVE_ANY_ASSETS": "کیا آپ کے پاس کوئی اثاثے ہیں",
  "DO_YOU_HAVE_BRUISE_OR_IRRITATION_IN_YOUR_FEET": "کیا آپ کے پیروں میں چوٹ یا جلن ہے",
  "DO_YOU_HAVE_DIABETES": "کیا آپ کو ذیابیطس ہے",
  "DO_YOU_HAVE_GOLD_SILVER": "کیا آپ کے پاس سونا چاندی ہے",
  "DO_YOU_HAVE_TRADE_ITEMS": "کیا آپ کے پاس تجارتی اشیاء ہیں",
  "DO_YOUR_HANDS_FEET_GET_NUMB": "کیا آپ کے ہاتھ پیر سن ہو جاتے ہیں",
  
  "DOES_ANYONE_IN_YOUR_FAMILY_HAVE_DIABETES": "کیا آپ کے خاندان میں کسی کو ذیابیطس ہے",
  "DOES_YOUR_EYE_FEEL_ITCHY": "کیا آپ کی آنکھ میں خارش ہے",
  "DON_T_BE_AFRAID": "خوف نہ کریں",
  "DON_T_PUT_PRESSURE_ON_YOUR_EYE": "اپنی آنکھ پر دباؤ نہ ڈالیں",
  "DON_T_WALK_WITH_BARE_FEET_ON_GRASS": "ننگے پیر گھاس پر نہ چلیں",
  "DURING_STUDIES_IS_YOUR_VISION_WEAK": "پڑھائی کے دوران کیا آپ کی نظر کمزور ہے",
  "DRY_YOUR_FEET_PROPERLY_AFTER_TAKING_A_BATH": "نہانے کے بعد اپنے پیروں کو اچھی طرح خشک کریں",
  
  "EYE_IS_RED": "آنکھ سرخ ہے",
  "FAMILY_MEDICAL_HISTORY": "خاندانی طبی تاریخ",
  "FEELING_OF_HOTNESS_OR_COLDNESS": "گرمی یا سردی کا احساس",
  
  "HOW_LONG_HAVE_YOU_BEEN_DIABETIC": "آپ کو ذیابیطس کتنے عرصے سے ہے",
  "HOW_LONG_HAVE_YOU_BEEN_FACING_THIS_PROBLEM": "آپ کو یہ مسئلہ کتنے عرصے سے ہے",
  "HOW_LONG_HAVE_YOU_BEEN_SUFFERING_WITH_THIS_DISEASE": "آپ اس بیماری سے کتنے عرصے سے بیمار ہیں",
  "HOW_LONG_HAVE_YOU_BEEN_WEARING_GLASSES": "آپ کتنے عرصے سے چشمہ پہن رہے ہیں",
  "HOW_MANY_KIDS_DO_YOU_HAVE": "آپ کے کتنے بچے ہیں",
  "HOW_MANY_TIMES_DO_YOU_PASS_URINE_AT_NIGHT": "آپ رات کو کتنی بار پیشاب کرتے ہیں",
  
  "IS_BLOOD_PRESSURE_HIGH_OR_LOW": "کیا بلڈ پریشر زیادہ ہے یا کم",
  "IS_HE_ELIGIBLE_FOR_ZAKAT_OR_DONATION_SUPPORT": "کیا وہ زکوٰۃ یا عطیات کی مدد کا اہل ہے",
  "IS_THE_LINE_STRAIGHT_OR_CROOKED": "کیا لائن سیدھی ہے یا ٹیڑھی",
  "IS_THIS_YOUR_FIRST_VISIT": "کیا یہ آپ کا پہلا دورہ ہے",
  "IS_THIS_YOUR_FOLLOW_UP_VISIT": "کیا یہ آپ کا فالو اپ دورہ ہے",
  "IS_YOUR_VISION_CLEAR": "کیا آپ کی نظر صاف ہے",
  
  "KEEP_YOUR_FEET_MOISTURIZED": "اپنے پیروں کو نم رکھیں",
  "NEED_CASH_PAYMENT": "نقد ادائیگی کی ضرورت ہے",
  "NEXT_TIME_BRING_CARD_WITH_YOU": "اگلی بار کارڈ اپنے ساتھ لائیں",
  
  "OPD_REFRACTION_DEPARTMENT": "او پی ڈی ریفریکشن ڈیپارٹمنٹ",
  "OPERATION_IN_YOUNG_AGE": "کم عمری میں آپریشن",
  "PAYMENT_FOR_BLOOD_TEST": "خون کے ٹیسٹ کی ادائیگی",
  "PEDIATRIC_DEPARTMENT": "اطفال کا شعبہ",
  "REGISTRATION_ROOM": "رجسٹریشن کمرہ",
  "REGULAR_CHECKUP": "باقاعدہ معائنہ",
  
  "TESTS_ARE_CHEAP_HERE": "یہاں ٹیسٹ سستے ہیں",
  "TESTS_ARE_EXPENSIVE_IN_OTHER_LABORATORIES": "دوسری لیبارٹریوں میں ٹیسٹ مہنگے ہیں",
  "THE_EYE_S_MEMBRANE_NEEDS_TO_BE_CLEAR": "آنکھ کی جھلی صاف ہونی چاہیے",
  "THE_RETINA_IS_WEAK": "ریٹینا کمزور ہے",
  
  "USE_COTTON_SOCKS": "سوتی موزے استعمال کریں",
  "USE_CREAM_BEFORE_WEARING_SOCKS": "موزے پہننے سے پہلے کریم لگائیں",
  "USE_FOOD_CHART": "کھانے کا چارٹ استعمال کریں",
  "USE_SIMPLE_SHOE_WITH_HALF_INCH_SOLE": "آدھا انچ تلے والا سادہ جوتا استعمال کریں",
  "USE_SMBG_SELF_MANAGEMENT_BLOOD_GLUCOSE": "خود بلڈ گلوکوز کا انتظام استعمال کریں",
  
  "VISIT_REFERENCE": "دورہ حوالہ",
  "WE_ARE_BEARING_ALL_YOUR_EXPENSES": "ہم آپ کے تمام اخراجات برداشت کر رہے ہیں",
  "WE_ARE_SUPPORTING_YOU_WITH_SOME_AMOUNT": "ہم آپ کو کچھ رقم سے مدد کر رہے ہیں",
  "WE_CAN_T_OPERATE": "ہم آپریشن نہیں کر سکتے",
  "WELFARE_SUPPORT_AMOUNT": "فلاحی مدد کی رقم",
  
  "WHAT_ARE_YOUR_EXPENSES": "آپ کے اخراجات کیا ہیں",
  "WHAT_IS_THE_CONDITION_OF_YOUR_CURRENT_GLASSES": "آپ کے موجودہ چشمے کی حالت کیا ہے",
  "WHAT_IS_YOUR_FATHER_S_NAME": "آپ کے والد کا نام کیا ہے",
  "WHAT_IS_YOUR_HUSBAND_S_NAME": "آپ کے شوہر کا نام کیا ہے",
  "WHAT_IS_YOUR_JOB": "آپ کا کام کیا ہے",
  "WHAT_IS_YOUR_MONTHLY_EARNING": "آپ کی ماہانہ آمدنی کتنی ہے",
  "WHAT_IS_YOUR_MONTHLY_SALARY": "آپ کی ماہانہ تنخواہ کتنی ہے",
  
  "WHEN_DID_YOU_HAVE_SURGERY": "آپ کی سرجری کب ہوئی",
  "WHEN_DO_YOU_NEED_THIS_REPORT": "آپ کو یہ رپورٹ کب چاہیے",
  "WHICH_MEDICINE_ARE_YOU_USING": "آپ کون سی دوا استعمال کر رہے ہیں",
  
  "YOU_HAVE_CATARACT_DISEASE": "آپ کو موتیے کی بیماری ہے",
  "YOUR_EYE_IS_LARGER_THAN_NORMAL_SIZE": "آپ کی آنکھ عام سائز سے بڑی ہے",
  "YOUR_EYE_IS_SMALLER_THAN_NORMAL_SIZE": "آپ کی آنکھ عام سائز"
};